#Ddatabase connection
Database:
  Type: MySQL
  Engine: InnoDB
  Module: jdbc
  Host: gamesny319.bisecthosting.com
  Port: 3306
  Name: s3309827_void
  User: u3309827_DafoqW9LKO
  Pass: 6AXKl5OdYyyHIdDIMagBJOpk
  allowPublicKeyRetrieval: true

# 
Token:

  #
  material: GOLD_NUGGET
  
  # 
  name: "&eArcade Token"
  
  # Item lore / description
  lore:
    - "&7Use to play a game at &6/warp arcade"
  
  # Max amount of token can be given out with one command
  # ~main inventory slots; tweak if you want. e.g., 64 * 36
  max_amount: 2304

Permissions:
  command: "arcade.cmd"
  command_help: "arcade.cmd.help"
  command_balance: "arcade.cmd.balance"
  command_balance_others: "arcade.cmd.balance_others"
  command_give: "arcade.cmd.give"
  command_take: "arcade.cmd.take"
  command_token: "arcade.cmd.token"
  command_reload: "arcade.cmd.reload"
  command_config: "arcade.cmd.config"
  command_enable: "arcade.cmd.enable"
  command_disable: "arcade.cmd.disable"
  command_export: "arcade.cmd.export"
  command_stats: "arcade.cmd.stats"

Language:

  # System
  prefix: "&7[#8D43B3A#9C4BCBr#AB52E2c#933BD0a#7C25BEd#640EACe&7]"
  coming_soon: "#B34343T#B8473Eh#BD4B39i#C24F34s #CC582Af#D15C25e#D76021a#DC641Ct#E16817u#E66D12r#EB710De #F57903i#F47205s #F26408c#F15E09o#F0570Bm#EF500Ci#EE490En#ED4210g #EB3413s#EA2E14o#E92716o#E82017n#E71919!"
  
  error_unknown_command: "&4Error! &cUnknown command %1."
  error_unknown_parameter: "&4Error! &cUnknown parameter (%1) for the command %2."
  error_no_permission: "&4Error! &cYou do not have permission to this."
  error_player_doesnt_exists: "&4Error! &cPlayer with the username %1 does not exists."
  error_player_is_not_online: "&4Error! &cPlayer %1 is offline."
  error_db_fail: "&4Error! &cCould not update the database."
  error_invalid_syntax: "&4Error! &cInvalid syntax."
  error_invalid_number: "&4Error! &c'%1' is not a number."
  
  # User
  balance: "&aYour ticket balance is currently at %1."
  give_success_target: "&7%1&a gave you &7%2&a ticket."
  take_success_target: "&7%1&e took &7%2&e ticket from you."
  take_partial_target: "&7%1&e tried to take &7%3&e ticket from you, but only &7%2&e was deducted."
  give_partial_target: "&a%1&a tried to give you &7%3&a ticket, but you got only &7%2&a (limit reached)."
  
  # Admin
  balance_others: "&e%1 currently has %2 tickets."
  give_success_sender: "&eYou gave &6%1 &eticket to &6%2&e."
  give_partial_sender: "&eYou tried to give &6%1 &eticket to &6%3&e, but only &6%2 &ewas applied (limit reached)."
  take_success_sender: "&eYou took &6%1 &eticket from &6%2&e."
  take_partial_sender: "&eYou tried to take &6%1 &eticket from &6%3&e, but only &6%2&e was removed."
  
  # Menus